name: Daily cronjob

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  cronjob:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: set private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > yub.key
          chmod 600 yub.key

      - name: cronjob
        run: |
          ssh -T -i yub.key -o UserKnownHostsFile=known_hosts -p "${{ secrets.PORT }}" "${{ secrets.USER}}@${{ secrets.HOST }}"
